"""
Tests for Step 17B - Persistent Vector Store & Dense RAG Engine
Validates:
- PersistentVectorStore record storage and disk persistence
- LocalDenseEmbedder normalized vector output
- Rich metadata schema per chunk (document_id, title, version, trust_level, owner, sensitivity)
- Structured retrieval metadata contract (search_with_metadata)
- Bounded context XML generation
"""

import os
import tempfile
import pytest
from rag.vector_store import PersistentVectorStore, LocalDenseEmbedder, cosine_similarity_vectors
from rag.rag_engine import RAGEngine
from security.security_controller import SecurityController


def test_dense_embedder_normalization():
    """Verify embedder outputs 128-dimensional normalized float vectors."""
    embedder = LocalDenseEmbedder()
    vec = embedder.embed("simulated fintech banking balance")
    assert len(vec) == 128
    # L2 norm check
    norm = sum(v * v for v in vec)
    assert abs(norm - 1.0) < 1e-4


def test_cosine_similarity_vectors():
    """Verify cosine similarity calculation between identical and orthogonal vectors."""
    vec_a = [1.0, 0.0, 0.0]
    vec_b = [1.0, 0.0, 0.0]
    vec_c = [0.0, 1.0, 0.0]

    assert abs(cosine_similarity_vectors(vec_a, vec_b) - 1.0) < 1e-6
    assert abs(cosine_similarity_vectors(vec_a, vec_c) - 0.0) < 1e-6


def test_persistent_vector_store_persistence():
    """Verify storing and reloading records from disk."""
    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
        tmp_path = tmp.name

    try:
        store = PersistentVectorStore(persist_path=tmp_path)
        store.add_record(
            chunk_id="chunk_1",
            content="Simulated customer transfer limits are ₹50,000.",
            metadata={"trust_level": "TRUSTED_INTERNAL", "source": "policy.txt"}
        )
        store.save()

        # Reload new store instance from same path
        store2 = PersistentVectorStore(persist_path=tmp_path)
        assert len(store2.records) == 1
        assert "chunk_1" in store2.records
        assert store2.records["chunk_1"]["metadata"]["trust_level"] == "TRUSTED_INTERNAL"
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


def test_rag_engine_rich_metadata():
    """Verify every chunk generated by RAGEngine has complete required Step 17B metadata."""
    rag = RAGEngine()
    results = rag.search("What is the daily transfer limit?")
    assert len(results) > 0

    chunk = results[0]
    assert "document_id" in chunk
    assert "source" in chunk
    assert "document_type" in chunk
    assert "title" in chunk
    assert "version" in chunk
    assert "trust_level" in chunk
    assert "created_at" in chunk
    assert "owner" in chunk
    assert "sensitivity" in chunk
    assert "chunk_id" in chunk
    assert "score" in chunk
    assert "content" in chunk


def test_rag_search_with_metadata_contract():
    """Verify search_with_metadata returns the required structured contract."""
    rag = RAGEngine()
    res = rag.search_with_metadata("KYC compliance passport verification")

    assert "query" in res
    assert "retrieved_chunks" in res
    assert "scores" in res
    assert "sources" in res
    assert "trust_levels" in res
    assert "count" in res
    assert len(res["retrieved_chunks"]) == res["count"]
    assert len(res["scores"]) == res["count"]


def test_fintech_policies_knowledge_document_ingested():
    """Verify newly added fintech_policies.txt is indexed and retrieved for approval queries."""
    rag = RAGEngine()
    res = rag.search("dual-control human approval threshold exceeding ₹50,000")
    assert len(res) > 0
    sources = [c["source"] for c in res]
    assert "fintech_policies.txt" in sources
    found = False
    for c in res:
        if c["source"] == "fintech_policies.txt":
            assert "50,000" in c["content"]
            assert c["trust_level"] == "TRUSTED_INTERNAL"
            found = True
            break
    assert found is True
